# Generated by Django 5.2.13 on 2026-05-11 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('kategorija', models.CharField(choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=2)),
                ('tip_menjaca', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('dostupan', 'Dostupan'), ('zauzet', 'Zauzet'), ('servis', 'Na servisu')], default='dostupan', max_length=10)),
                ('napomena_statusa', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('teorija', 'Teorija'), ('voznja', 'Vožnja')], max_length=10)),
                ('status', models.CharField(choices=[('slobodan', 'Slobodan'), ('zakazan', 'Zakazan'), ('odrzan', 'Održan')], default='slobodan', max_length=10)),
                ('datum_vreme', models.DateTimeField()),
                ('trajanje_min', models.IntegerField(default=60)),
                ('napomena', models.TextField(blank=True)),
                ('instruktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predaje', to=settings.AUTH_USER_MODEL)),
                ('kandidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casovi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['datum_vreme'],
            },
        ),
        migrations.CreateModel(
            name='NapredakKandidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teorija_odradjeno', models.IntegerField(default=0)),
                ('teorija_ukupno', models.IntegerField(default=10)),
                ('voznja_odradjeno', models.IntegerField(default=0)),
                ('voznja_ukupno', models.IntegerField(default=40)),
                ('ocena_instruktora', models.FloatField(default=0)),
                ('kandidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='napredak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
